<!--
  ~ Copyright (c) 2018-2023, Entgra (Pvt) Ltd. (http://entgra.io) All Rights Reserved.
  ~
  ~ Entgra (Pvt) Ltd. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<!DOCTYPE assembly [
        <!ELEMENT assembly (id|formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode|filtered)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes)*>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|filtered|destName)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        ]>
<assembly>
    <id>bin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>

    <fileSets>
        <fileSet>
            <directory>../../p2-profile/target/${entgra-iot-core}</directory>
            <outputDirectory>${entgra-iot-community}</outputDirectory>
        </fileSet>
    </fileSets>

    <files>
        <file>
            <source>src/temp.txt</source>
            <outputDirectory>${entgra-iot-community}/</outputDirectory>
        </file>
    </files>

</assembly>
